[package]
name = "SimbaPlugin"
version = "0.1.0"
edition = "2021"
description = "SimbaPlugin"

[lib]
name = "simba_plugin"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
winapi = { version = "0.3", features = ["libloaderapi"] }